# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  RainbowFileExplorer_config = debug
endif
ifeq ($(config),release)
  RainbowFileExplorer_config = release
endif
ifeq ($(config),dist)
  RainbowFileExplorer_config = dist
endif

PROJECTS := RainbowFileExplorer

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

RainbowFileExplorer:
ifneq (,$(RainbowFileExplorer_config))
	@echo "==== Building RainbowFileExplorer ($(RainbowFileExplorer_config)) ===="
	@${MAKE} --no-print-directory -C Explorer -f Makefile config=$(RainbowFileExplorer_config)
endif

clean:
	@${MAKE} --no-print-directory -C Explorer -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   RainbowFileExplorer"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"