name: build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: RainbowToolBox.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Dist

permissions:
  contents: read

jobs:
  build-win32:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta2"

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build SDL2 statically
        run: |
          git clone https://github.com/libsdl-org/SDL.git
          cd SDL
          git checkout SDL2
          cd VisualC
          msbuild SDL.sln -target:SDL2:Rebuild -verbosity:diag -property:Configuration=Release -property:Platform=Win32 -property:DefineConstants="HAVE_LIBC;SDL_STATIC_LIB" -property:ConfigurationType=StaticLibrary -property:RuntimeLibrary=MT
          copy /Y Win32/Debug/*.* ../../External/SDL2/lib/x86-static-release

      - name: Prepare MSVC project files
        run: premake5 --file=Build.lua vs2022

      - name: Upload Rainbow File Explorer
        uses: actions/upload-artifact@v4
        with:
          name: Rainbow File Explorer (Windows)
          path: Binaries/windows-x86/Dist

  # build-ubuntu64:
  #   runs-on: ubuntu-22.04

  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: abel0b/setup-premake@v2.4
  #       with:
  #         version: "5.0.0-beta2"

  #     - name: Install dependencies
  #       run: sudo apt-get install libgl1-mesa-dev

  #     # - name: Install Dependencies
  #     #   run: sudo apt-get install libsdl2-dev

  #     # - name: Install dependencies
  #     #   run: |
  #     #     sudo apt-get update
  #     #     sudo apt-get install -y build-essential libx11-dev libxext-dev libxrandr-dev libxrender-dev libxinerama-dev libxi-dev libxcursor-dev libasound2-dev libpulse-dev libgl-dev libgl1-mesa-dev libgl1

  #     # - name: Build SDL2 statically without DYNAPI
  #     #   run: |
  #     #     git clone https://github.com/libsdl-org/SDL.git
  #     #     cd SDL
  #     #     git checkout SDL2
  #     #     mkdir build
  #     #     cd build
  #     #     ../configure --enable-static --disable-shared
  #     #     make
  #     #     sudo make install

  #     - name: Generate make file
  #       run: premake5 --cc=clang --file=Build.lua gmake2

  #     - name: Build
  #       run: make config=dist

  #     - name: Upload Rainbow File Explorer
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: Rainbow File Explorer (Linux)
  #         path: Binaries/linux-x86_64/Dist

  # build-macos:
  #   runs-on: macos-13

  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: abel0b/setup-premake@v2.4
  #       with:
  #         version: "5.0.0-beta2"

  #     - name: Generate make file
  #       run: premake5 --cc=clang --file=Build.lua gmake2

  #     - name: Build
  #       run: make config=dist

  #     - name: Upload Rainbow File Explorer
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: Rainbow File Explorer (macOS)
  #         path: Binaries/macosx-universal/Dist
